### ISSUE TITLE
Update EmojiList

### ISSUE THREAD

**Issue by niklasgrewe** [ReactComponentKit/ListKitExamples#1]
Hi, thank you to showing us, how can we use `ListKit`, awesome great examples 👍 Is there a special reason why you create a new snapshot and apply it in the [updateSnapshot()](https://github.com/ReactComponentKit/ListKit/blob/ad970d54379a3e137e5bbb8f5bacf2c93b9e66f2/Sources/ListKit/DataSource/DiffableDataSource.swift#L70) function, instead of updating the initial snapshot you already have?

Can this cause performance problems if you always create a new snapshot instead of updating the existing one?

Also i am interesting to using Combine with `@Published` properties. Could you maybe add an example with Combine. That would be really cool. Thank you

**Comment by skyfe79** [comment]
@niklasgrewe Hi, niklasgrewe. First of all, thanks for your concern. the reason why create the new snapshot in updateSnapshot() is [recofigureItems](https://developer.apple.com/documentation/uikit/nsdiffabledatasourcesnapshot/3804468-reconfigureitems) is available  on iOS 15.0+. and along with [the document](https://developer.apple.com/documentation/uikit/views_and_controls/collection_views/updating_collection_views_using_diffable_data_sources).
> The only mechanism to update the data for existing items is to apply a new snapshot containing the new data structures, which causes the diffable data source to perform a delete and an insert for each changed item.

I will implement an example using ListKit and Combine. before that it will be good chance to check out my other open source [Redux](https://github.com/ReactComponentKit/Redux).

thanks. 😊
